name: batch

on:
  schedule:
    - cron: '00 23 * * *'
  workflow_dispatch:

jobs:
  batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Git settings
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install
        run: pip install -r requirements.txt

      - name: Run
        run: |
          python run.py > num.txt
          cat num.txt

      - name: Check num.txt
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          bash notify.sh
          git config -l
